### Recuperar todas las pelis
GET http://localhost:3000/movies

### Recuperar peli por ID
GET http://localhost:3000/movies/aae5b8b6-e213-43f2-bb45-ba5ceb06f161

### Recuperar peli por genero - Con QueryParams
GET http://localhost:3000/movies?genre=Action

### Crear una peli
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "Arcadian",
    "year": 1996,
    "director": "Tarantino",
    "duration": 1994,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre":"Action",
    "rate": 5
  }

### Actualizar solo una parte de la peli
PATCH http://localhost:3000/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0
Content-Type: application/json

{
  "year": 2023
}

### Borrar una pelicula
DELETE http://localhost:3000/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0
